### ISSUE TITLE
ask a question function not working

### ISSUE THREAD

**Issue by kseggelke918** [learn-co-curriculum/programming-univbasics-4-looping-with-arrays#1]
The "Ask a Question" button is grayed out and I am not able to click it to ask a question about the code I'm trying to write.  The "Question Need Help" button is also grayed out.  I have opened multiple different courses and am having the same issue with all of them.

**Comment by maxwellbenton** [comment]
Hi @kseggelke918,

Thank you for spotting this and providing feedback. We were able to look into this issue and get the Ask a Question button activated for the prework content. Some courses may not have AAQ activated, but prework definitely should, so thank you for pointing out this bug to us. If you visit this lesson or any other prework lessons and hard refresh (on Mac, that's Command + Shift + R), the AAQ button should appear activated on refresh.

We believe this issue should now be resolved for prework, but if it is not, please reopen this issue. Also, if you are continuing to experience this on other courses, please feel free to open an issue on a lesson on one of those courses as well.

Thank you!
